### ISSUE TITLE
Misspelled [About] on github

### ISSUE THREAD

**Issue by bronze** [surjithctly/neat-starter#11]
Hi.
It says "Alphine JS" on the About sidebar. 
I believe it should be "Alpine JS".

**Comment by surjithctly** [comment]
Do you mean, in README? it's fixed now. Any other places?

**Comment by bronze** [comment]
![image](https://user-images.githubusercontent.com/170220/120903088-86537d80-c61a-11eb-9546-0a8658bf2d02.png)

on the sidebar, to the right

**Comment by surjithctly** [comment]
Fixed. Thanks
