### ISSUE TITLE
Markdown in frontmatter doesn't get HTML tags in output

### ISSUE THREAD

**Issue by wohfab** [surjithctly/neat-starter#7]
Hey there,

I am using your starter and it is really amazing! One issue I ran into is, that when I have a markdown field in my data frontmatter, it just gets output as one line of text with no HTML tags, thus not preserving paragraphs etc.

Maybe you have an idea, how to fix that?

**Comment by surjithctly** [comment]
Hello,

It should work fine if the yaml & markdown plugin formatting it correctly. may be do a console.log on it to see if it returns expected output. 

or, send me some code example where I can replicate the issue. 

~Surjith

**Comment by wohfab** [comment]
Thanks for the quick reply! I got it working with the filter [in this issue comment](https://github.com/11ty/eleventy/issues/1380#issuecomment-698457560).

Adding this to `.eleventy.js`:

```
  eleventyConfig.addFilter("md", function (content = "") {
    return markdownIt({ html: true }).render(content);
  });
```
